name = "replyflix"
main = "worker.js"
compatibility_date = "2026-09-26"

[vars]
ALLOWED_ORIGIN = "https://replyflix.dewify.shop"

[[d1_databases]]
binding = "DB"
database_name = "replyflix"
database_id = "d7fef1fc-b642-485c-b9d7-13ace667f845"

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[routes]]
pattern = "api.replyflix.dewify.shop"
custom_domain = true

[[routes]]
pattern = "replyflix.dewify.shop"
custom_domain = true
