name = "replyflix-api"
main = "worker.js"
compatibility_date = "2026-09-26"

[vars]
ALLOWED_ORIGIN = "https://tori.dewify.shop"

[[d1_databases]]
binding = "DB"
database_name = "replyflix"
database_id = "d7fef1fc-b642-485c-b9d7-13ace667f845"
